POST http://127.0.0.1:8080/api/user/login
Content-Type: application/json

{
	"email":"artem.szagarov@test3.com", 
	"password": "1234567890"
}

###

POST http://127.0.0.1:8080/api/user/user
Content-Type: application/json

# {
# 	"email":"artem.zagarov@gmailw.com", 
# 	"password": "12345678"
# }

###

POST http://127.0.0.1:8080/api/user/register
Content-Type: application/json

{
	"email":"artem.szagarov@test3.com", 
	"password": "12345678",
	"name": "osuzhdayu"
}

###
POST http://127.0.0.1:8080/api/user/update
Content-Type: application/json

{
	"password": "1234567890",
    "city":"normal1",
	"name": "osuzhdayu2"
}

###
POST http://127.0.0.1:8080/api/user/signout
Content-Type: application/json

###
POST http://127.0.0.1:8080/api/item/create
Content-Type: application/json

{
    "_id": "606f53ded540f3156a84c616",
    "name": "string",
    "description": "string",
    "image": "string",
    "sizes": ["35-3u"],
    "inStock": 4.0,
    "price": 0,
    "color": "string",
    "availiableColors": ["string[]"],
    "season": "string",
    "structure": {"check":"1"}
}

###

POST http://127.0.0.1:8080/api/item/update
Content-Type: application/json

{
    "_id": "606f53ded540f3156a84c616",
    "name": "string",
    "description": "string",
    "image": "string",
    "sizes": ["35-3u"],
    "inStock": 4.2,
    "price": 0,
    "color": "string",
    "availiableColors": ["string[]"],
    "season": "string",
    "structure": {"check":"1"}
}

###

POST http://127.0.0.1:8080/api/item/remove
Content-Type: application/json

{
    "_id": "60758944ccf22a3322b0b2bc"
}
###